### ISSUE TITLE
use memory mapped files to support 2^63 big fits files

### ISSUE THREAD

**Issue by ritchieGitHub** [nom-tam-fits/nom-tam-fits#100]
redesign the underlaying file api to use memory mapped files, and support files up to the size that fits in a long (2^63).

**Comment by attipaci** [comment]
I'm not sure memory mapped files will overcome this limit easily, since `MappedByteBuffer` has the same 32-bit address limit as arrays, despite the interface having a `long` argument for position.

**Comment by mbtaylor** [comment]
I have been using memory-mapped files alongside (a very old fork of) nom.tam.fits for many years.  This is done within the [STIL](http://www.starlink.ac.uk/stil/) table I/O library (which underlies TOPCAT/STILTS).

Short history: I started to use nom.tam.fits for FITS I/O, figured out that although the header handling etc was OK for my purposes the bulk data handling did not suit my performance requirements, and rewrote various parts (BINTABLE I/O and low-level I/O) from scratch.  Initially I wrote two new `nom.tam.util.ArrayDataInput` implementations, [uk.ac.starlink.fits.MappedFile](https://github.com/Starlink/starjava/tree/master/fits/src/main/uk/ac/starlink/fits/MappedFile.java) based on a single `ByteBuffer`, and [uk.ac.starlink.fits.MultiMappedFile](https://github.com/Starlink/starjava/tree/master/fits/src/main/uk/ac/starlink/fits/MultiMappedFile.java) based on multiple ByteBuffers (for files >2^31 bytes). I've since refined my implementation code further, so these classes are no longer in much use.  If you want to look at this code for reference or pinch it, feel free ([javadocs](http://www.star.bristol.ac.uk/~mbt/stil/javadocs/) also available).

**Comment by attipaci** [comment]
I did not know about STIL. It sounds interesting... Do you think you would want to work on integrating your starlink work into the mainline for 2.0? I think it's about time to leap boldly into the future. The current API is reaching the limits of what it can do without serious contortions. It's probably time to rethink the API fundamentally going forward... However, that's not something I want to (or care to) do alone. Nor do I have that kind of time on my hand to work on something as big really, but I'd be happy to contribute... If we can build a team of a few interested devs, then we could start brainstorming an experimenting. And, if things go well, we could maybe get a 2.0 out in a year or maybe 2...
