### ISSUE TITLE
Limitation: table rows are described by Int and not Long

### ISSUE THREAD

**Issue by JulienPeloton** [nom-tam-fits/nom-tam-fits#128]
Hi,

Thanks for the nice library!

I recently noticed that table rows are described by Int (think about getRow(index_row) for example). Therefore we get a limitation regarding the maximum number of rows (2^31 -1). For current data set, this can be easily reached... Would it be possible to switch to Long instead?
I would be happy to help in this matter if needed (PR).

Julien

**Comment by ritchieGitHub** [comment]
Sorry for the delay ... I was on a very long trip -> offline for a few Months ;-)
I will try to restart the comming weekend

**Comment by JulienPeloton** [comment]
No problem and no rush - I found another solution to my problem!

**Comment by attipaci** [comment]
Hi Julien!

I'm taking over the maintaining of the repo from Ritchie. You aren't the only one who want into this limitation. In principle it should be possible to change from `int` to `long` for table row access, but the questions are (a) how deep one has to go to make it happen, and (b) if this may break backward compatibility for existing code. My guess is that the first part should be doable with moderate effort (would you like to try make the change on a fork an submit it as a pull request?). The second question can be more thorny, since we aim to preserve backward compatibility as much as possible. That does not mean we cannot break backward compatibility under any circumstance, but that we must be very sure of why we do that if we do...

In any case, I'll be happy to stay engaged if you are still interested on resolving this.

**Comment by attipaci** [comment]
Julien, I think this is essentially the same issue as #131 , where we began a discussion on how to approach this, if it is possible at all. So, I'll close this ticket as a duplicate (even though this is the earlier one). But we can reopen it if you feel like the other one does not capture the issue well enough...

**Comment by attipaci** [comment]
I am reopening this ticket since #131 is not quite the same issue, though related... In any case, a comment I made there might apply to your issue better:

> I did take a peek last night, and `getMemoryRow(int)` does use Java arrays like you mention to locate the data -- so once the `BinaryTable` has been fully read, it would require a major rewrite on how we store and access column data. However, `getFileRow()` should readily handle larger values, since it repositions in the file to the element (which uses long) to read... I think there is rationale to that if you have more than 2^31 rows, you probably don't want to read them all at once in anyway... So, perhaps, we can support more rows by:
>
> - Changing `getRow(int)` to `getRow(long)`...
> - For tables with more than 2^31 rows, we don't even attempt to read the table into RAM...
> - `getRow(long)` to throw an `ArrayIndexOutOfBoundsException` whenever the requested row is larger than the number of rows (whether loaded in RAM or not)
>
> What do you think?

**Comment by attipaci** [comment]
Well, it's not as isolated a change as I thought it might be. Ritchie did plan to reimplement the data handling to used memory mapped files (see #100), which he slated for the next major upgrade. Doing something like that would solve the issue much better than trying to patch up the existing combination of in-memory, and file access to tables... Unfortunately, I don't think anyone is currently working on implementing memory mapping for the data... So, it may be a long time before we get there...
