### ISSUE TITLE
Fits.getNumberOfHDUs() method always returning 0?

### ISSUE THREAD

**Issue by supermartzin** [nom-tam-fits/nom-tam-fits#13]
This is more question then bug but I couldn't find something about this in documentation.

When I load a FITS File:
```java
Fits fits = new Fits(fitsFile);
```
and then call for number of HDUs:
```java
fits.getNumberOfHDUs();
```
it always returns **0** even if there is at least 1 HDU

I found out that I must call method 
```java
fits.read();
```
before and then call for a number of HDUs in file.

Is this an expected behaviour? Because if it is, it would be really nice to point it out in documentation.
Thanks :)

**Comment by TomMcGlynn** [comment]
This is the expected behavior, but I agree that the documentation for the FITS constructors could be clearer.  When a FITS object is created using any of the constructors it is empty.  The documentation for the Fits(String) constructor says that the  "Fits object is associated with the file" which means that if you use the Fits.read() methods, that the HDU read back will be added to the Fits object.  However you can add HDUs in other ways.

E.g., you could have
   Fits f = new Fits('xx.fits');
   f.addHDU(some HDU read earlier from another file);
   f.read();

and the first HDU in the file xx.fits will be read in as the second HDU in the Fits object.

This is true of all of the Fits constructors.  The JavaDocs for the FITS class allude to this a little discussing how they do I/O on the HDU level, but it's not explicit.

If you want to make an in-memory counterpart to an external FITS file then you need to do
    Fits f = new Fits("file");
    f.readAll();

**Comment by supermartzin** [comment]
Yeah, you're right, I didn't realized that the `Fits` object is just an abstraction and it would be unefficient to load whole existing file to memory when one of the appropriate constructors used.
