### ISSUE TITLE
fork notice

### ISSUE THREAD

**Issue by pdowler** [nom-tam-fits/nom-tam-fits#147]
Hi,

We are using this library for some new development in OpenCADC for deployment at CADC and ALMA data centres and need to extend in various ways. I would prefer to push changes upstream but it looks like development here is stalled or dead and I have not been able to contact the owner of this repo and organisation.

We will by necessity be publishing our fork, but will do so under a our own maven group (org.opencadc) to avoid confusion. I will do my best to make it feasible to re-integrate and abandon our fork if something changes and we would be willing to take over or help maintain here instead of in opencadc.

**Comment by attipaci** [comment]
Hi there,

I'm taking over from Ritchie in managing this repo (at least for now). My goal is to provide at least a basic level of maintenance, but I'll be willing to integrate bigger changes enhancements also, so long as they play nicely with the test cases, and they provide sufficient (close to 100% coverage) for any new/changed code. Please feel free to make pull request especially if you make changes that may benefit the wiser user community.

**Comment by pdowler** [comment]
I'll have to look at our repo and see if it is feasible to submit a sequence of smaller pull requests; if not, it might have to be one big PR which would be hell to review (I know because I reviewed the smaller ones). We did try to maintain comaptibility with the existing API.

Some details:

The work itself was to enable using the library to stream a FITS file from an underlying (non-filesystem) storage system (in our case, CEPH object store) and perform operations on it like extracting extensions or subsets of pixels. The motivation is to implement the IVOA SODA operations on top of the object store in an efficient way, so the implementation does the operations during the read and dumps it all to an approp output). The changes are needed for s/w used at CADC and ALMA. Most of our changes are in service of that goal.

There are some side things we did, like using gradle to build and run the tests (at the time, the version of maven you could use via github actions wouldn't work because of a version conflict with one of the plugins). This is separable but I thought I'd mention it.

**Comment by attipaci** [comment]
That sounds excellent work that you did there!

I'm not sure we have the manpower to properly review PRs carefully. It's really a community maintained lib, and my approach is to trust the devs for the most part. As long as the API is not changed much (additions excepted), and the existing test cases pass, and provided the overall code coverage is not decreasing -- the merge should be straightforward...

If there are significant changes to the API, or existing behavior, we might just have to designate it for the next major release (e.g. 2.0), rather then the next minor release (e.g. 1.16) but that should not be a showstopper either ...

You should of course merge/rebase your changes to the mainline master before making a PR (that goes without saying really). Most of the changes I have been incorporating since 1.15.2 affect the header processing only, and not much beyond. As such, I expect merging the changes you describe would be relatively conflict free... (And if not, we can discuss how to resolve conflicts that arise if it's not obvious)...

I think the most important bit is to provide nearly 100% test coverage for any new code you submit or change. I presume you probably do that already, so it should not be a big ask...

In any case, let me know what you think... I'm happy to help as much as I can (which is probably no much...)

**Comment by attipaci** [comment]
I think this ticket can be closed. I do hope that you'll move ahead with some pull requests in the future to merge some or all of the work you did for CADC and ALMA. I'd very much like to see them in the mainline :-)
