### ISSUE TITLE
automatic HIERARCH keyword handling

### ISSUE THREAD

**Issue by ritchieGitHub** [nom-tam-fits/nom-tam-fits#19]
as specified in http://heasarc.gsfc.nasa.gov/fitsio/c/f_user/node28.html the HIERARCH keyword could be handled automaticaly as soon as a keyword is to long or contains a '.' or a blank.

proposed by  @tony-johnson  in #16

**Comment by TomMcGlynn** [comment]
If the idea here is simply that after the user has done 
   FitsFactory.setUserHierarch(true)
that any of these conditions can trigger a HIERARCH keyword, then I think that's fine.  Note however
that the embedded "." may be a special case.  In the current support for hierarch keywords "." is used to separate values in the keyword.  So 
   addValue("HIERARCH.A.B.C"  ->  HIERARCH A B C
which is in accord with the actual ESO convention and is presumably how current users of the library use it.  Presumably that should stay the same.  However you're proposing that the user need not
have the initial HIERARCH.  So do we want:
  addValue("A.B.C"    -> HIERARCH A.B.C
 or                                   HIERARCH A B C

The ESO convention requires that each token use the same set of characters valid in header keywords while CFITSIO is more liberal.  My inclination would be for the later since it seems more consistent with the library's current usage.  This precludes creating cards of the first format entirely which is either a good thing -- if you believe that the ESO convention should rule, or a bad thing if those are the kind of keywords you want (as had been requested earlier).  I don't have very strong feelings here but the choice should be carefully documented in the JavaDocs.

I'd be a bit more  concerned if automated creation were done even if the user has never indicated an interest in HIERARCH.  It may be better for this keyword to fail or be fit into the standard schema if the next step in the user's processing is a library that doesn't recognize HIEARCH keywords. However you might add something like: 
   FitsFactory.setNoHierarch(); // or something similar
flag to make it possible for users to  forbid the creation of HIERARCH keywords.  Then I think it would be OK.  Presumably then the setUseHierarch method would be deprecated, since the default behavior would be to accept values (though I guess it might be useful to override the an environment set value as set in the next value).

To ensure  backwards compatibility it might be of interest to allow this flag (or maybe all the similar flags defined in FitsFactory) to be set using the environment or a Java system setting, so users can use their same code without any recompilation necessary with new versions of the library.

**Comment by TomMcGlynn** [comment]
Didn't mean to close, clicked on the wrong button.

**Comment by ritchieGitHub** [comment]
good, should we then not use system properties for that? or both? I would propose the system properties:
```
    nom-tam-fits.useAsciiTables
    nom-tam-fits.noHierarch
    nom-tam-fits.checkAsciiStrings
    nom-tam-fits.allowTerminalJunk
    nom-tam-fits.longStringsEnabled
```
and the environment values
```
    NOM_TAM_FITS_USE_ASCII_TABLES
    NOM_TAM_FITS_NO_HIERARCH
    NOM_TAM_FITS_CHECK_ASCII_STRINGS
    NOM_TAM_FITS_ALLOW_TERMINAL_JUNK
    NOM_TAM_FITS_LONG_STRINGS_ENABLED
```
that would work for everybody. the precedence would be:
 environment, system-property, default
  
@TomMcGlynn do you agree?

**Comment by TomMcGlynn** [comment]
The way I use system properties, I'd set them in the command running the 
actual Java executable, so for me it would make more sense for them to 
have priority over the environment -- which I might set in some login 
script that I ran a thousand requests ago.  However others may do things 
differently, so I'd be very happy with the arrangement as given.

Perhaps -- if there are to be more of these in the future -- we should 
just ahave some state hash that the initialization code that sets.  The 
specific instances we have now would be convenience methods so
     setUseAsciiTables(true)
simply calls
     setFitsState("USE_ASCII_TABLE", true)
and we also have
     getFitsState("USE_ASCII_TABLES")

The initialization code could look for any values that have the 
appropriate prefix in the environment or system properties.

Just thinking aloud here.  Then if we want to put in a flag for -say- 
compressing images by default, then we just add a new value in the hash.

     Tom

Richard van Nieuwenhoven wrote:

**Comment by ritchieGitHub** [comment]
Even better so the priority would be:
system-property, environment, default

But we should use ThreadLocal (see #21 ) and static var's to store the object because getting a system property so many times is very slow.

**Comment by TomMcGlynn** [comment]
I guess I was thinking that at the time the library started up there 
would be a one time check of the environment and the system properties,
but I wasn't contemplating a web container environment like TOMCAT.  
Since TOMCAT can re-use threads, I'm not sure even a thread local is 
really satisfactory.

E.g., in request A the user could have updated the value of one of the 
flags, and that change would still be visible when that thread was 
reused in request B even though the user there might be completely 
unaware of request A and just wants the default.

If you are going to worry about general multi-threading and reusable 
thread pools, seems like you need a FitsFactory.reset() method (or some 
such) or the user needs to set each flag explicitly.

     Tom


Richard van Nieuwenhoven wrote:

**Comment by ritchieGitHub** [comment]
That, why I wanted to set one Dialect object with all the settings at once this can be so stored in the session and reactivated on every request iin the  session.

**Comment by TomMcGlynn** [comment]
Seems reasonable.

**Comment by attipaci** [comment]
The requirement that HIERARCH keywords are processed automatically is now met after merging pull request #125 (`setUseHierarch(true)` by default), and #153 (fixes and improvement to keyword parsing). The user can still disable the processing of HIERARCH keywords, as an option, by calling `setUseHierarch(false)`. As such I consider this issue closed.
