### ISSUE TITLE
make all dependencies optional

### ISSUE THREAD

**Issue by ritchieGitHub** [nom-tam-fits/nom-tam-fits#20]
For users that do not use an idea or build tools it is important that no other dependencies are needed.

@TomMcGlynn  this means the discussion thread about compression lib is not nessesary anymore, I now understand what you want to provide to the library users.

**Comment by TomMcGlynn** [comment]
In a general sense I'm not sure I'd go quite so far.  If the dependency 
is universal -- i.e., every or nearly every use of the library is going 
to require the dependency then there's no real benefit to making it 
optional.  E.g., one could imagine a situation in which there is some 
library that for copyright reasons needs to be kept separate but is used 
in most invocations.  In practice I don't think we currently have 
anything like that in the FITS library.  I do think it makes things much 
nicer when the users don't have to include rarely used libraries like 
bzip2 so that the FITS library can be distributed as a single file.  
Thanks for this change!

Richard van Nieuwenhoven wrote:

**Comment by ritchieGitHub** [comment]
Currently it's only bzip2 but I mean it in a more general sense. For example logging, normally I would introduce slf4j. The most current logging library. But deu to this issue I would not do that anymore and use JUL (the jre logging) instead. To keep the dependencies minimal.

**Comment by ritchieGitHub** [comment]
done, the decompression is now expendable by the user. Now also has fall-backs to Apache-compress if the Z decompress was not available on the system. If the Apache-compress lib is not available the other decompressors still function as expected.
