### ISSUE TITLE
tile compression

### ISSUE THREAD

**Issue by ritchieGitHub** [nom-tam-fits/nom-tam-fits#23]
the tile compression feature is currently not supported, should we support it? There are multiple ways to do this. One is to port the CFITSIO compressions to java or we could access the  CFITSIO per JNI for tile compression like the python filts lib does?

**Comment by ritchieGitHub** [comment]
@TomMcGlynn could you give an impression of how important the support of tiled compression would be? Implementing this rather complicated stuff for 0.001% usage would be a waste of time but if it is rather common... Another possibility would be to support it only readonly?

**Comment by TomMcGlynn** [comment]
Hi Ritchie,

This is difficult for me to judge. The usage of compressed images is coming from the domains where 
there are very large images.  If you have a 10K x 10K images which is not unusual in ground-based 
instrumentation, then you've got 100 megapixels and it can be painful to try to manipulate the whole 
image at once.  Since your underlying camera may be a 10x10 array of CCDs representing the image as 
a set of tiles can make a lot of sense.  So I believe this format is gaining some traction in the 
ground community.  However these large images are not something that comes up much in space-borne 
missions (though I think JWST may look at it) so I haven't personally used these conventions much, 
and in high energy astronomy we rarely have sufficient resolution to worry about images that large. 
  That's why that code never got finished.

While readonly support might be a stopgap, it makes it a bit more difficult to do testing since 
you'll need to use another library.  I don't think that the compression is particularly more 
difficult than the decompression.

	Tom

Richard van Nieuwenhoven wrote:

**Comment by ritchieGitHub** [comment]
implemented
