### ISSUE TITLE
copy a binary table by its data?

### ISSUE THREAD

**Issue by ritchieGitHub** [nom-tam-fits/nom-tam-fits#24]
When copying a binary table by the internal column-data the geometry is different. 
```java
BinaryTable btab;
...
new BinaryTable((ColumnTable)btab.getData())
```
is this intended or a bug? See the to do in BinaryTableTest!

**Comment by TomMcGlynn** [comment]
Richard van Nieuwenhoven wrote:
> When copying a binary table by the internal column-data the geometry is different.
>
> BinaryTable  btab;
> ...
> new  BinaryTable((ColumnTable)btab.getData())
>
> is this intended or a bug?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nom-tam-fits/nom-tam-fits/issues/24>.
>

If I understand it, you're asking why the internal representation of data in binary tables, 
ColumnTable,  is column oriented while the actual FITS data is row oriented?  If so, then this is 
very much intended.

Consider a typical binary table at the HEASARC, an event list with with 20 columns and 1 million 
rows.  We could store this in a structure where the data are allocated in the same order as the data 
are present in the file.  However given that
   - adjacent columns are often different data types
   - we want users to be able to change individual entries (so we can't store things as int's we need
to store them as int[1] so that the value can be altered)
then each field in the table is normally rendered as a separate object.

However if we put store in column order, then for all of the numeric scalars (which tend to be the 
vast bulk of the data) we can store an entire column in a single object.  So you might be able to 
store everything in just 20 objects.

At least in the first several versions of Java the difference between allocating 20 objects and 
allocating 20 million was very significant in both CPU performance and memory. I've not looked at 
this since <~Java 1.4 and I wouldn't be surprised if the penalty is now rather less, but I'd guess 
it's still substantial -- but that is just a guess.  There is less benefit for tables containing 
strings or where the individual entries are arrays, but in my experience large (i.e., >> 10^6 row) 
tables of numeric scalars are pretty common.

	Tom

P.S., Often there are one or two string columns in the table to go with the numeric scalars. So more 
realistically the difference is between 20M objects and 1-2M objects.  However in many cases the 
string values have only a few different values.  One vagrant thought when writing this was whether 
the cost of interning strings in binary tables might be offset by the fact that many actual string 
objects would need to be created.

**Comment by ritchieGitHub** [comment]
So it is intendet that a new binarytable created with the internal columntable of another  binarytable results in a different geometry binary table.

Could you then create a unit test for the constructor of a binarytable where the parameter is a columntable an the result makes sense 😄

**Comment by TomMcGlynn** [comment]
Hmmm....  I didn't think it did that -- though I haven't looked at it.  The idea was that
the ColumnTable is the way binary tables are represented internally, so when you write out an HDU 
that was generated from a column table it should have the same structure as the structure of the
table from which the ColumnTable was generated.

	Tom

Richard van Nieuwenhoven wrote:

**Comment by TomMcGlynn** [comment]
With regard to where a user would use the ColumnTable constructor.  Again it is my belief that this 
preserves the structure of the original FITS table.  If so, then the column table constructor should 
be the most efficient way of making a copy of the BinaryTable.  You might try something like

     BinaryTable copy = BinaryTable((ColumnTable)original.getData());
     for (int i=0; i<copy.getNRows(); i += 1) {
         copy.setElement(i, 3, (Integer)(2*(int)copy.getElement(i,3));
     }

and compare the original and copied HDU.

	Tom

Tom McGlynn wrote:

**Comment by ritchieGitHub** [comment]
here the test that (set to ignore)
nom.tam.fits.test.BinaryTableTest.buildByRowAfterCopyBinaryTableByTheColumnTable()

**Comment by ritchieGitHub** [comment]
fixed by @TomMcGlynn
