### ISSUE TITLE
API for incremental HDU writing

### ISSUE THREAD

**Issue by keastrid** [nom-tam-fits/nom-tam-fits#266]
Forgive me if I have missed something.

When trying to incrementally write a large file to disk, in this case writing a multi-HDU file comprised of several 2D image HDUs, it is necessary to properly setup the headers, which is handled by at the higher level automatically by `Fits#addHDU` ultimately calling `BasicHDU#setPrimaryHDU`, which is protected, and therefore the higher-level write functionality cannot be replicated with the lowlevel API without reimplementing that method.

**Comment by attipaci** [comment]
Hi!

I'm not sure I fully understand the issue. My feeble understanding is that you are trying to write a number of HDUs to a file directly, bypassing a `Fits` object to handle it properly. The `Fits` object would be the one that ensures that only the first HDU is set as primary, and never any other. 

Could you not just add the HDUs to a `Fits` first and then write it out? Or else, just add the first HDU to a `Fits` and write it out. Then you can pile on the additional HDUs to the stream to your heart's content any time after that. That way the first HDU will be properly made primary, and still allow you to write HDUs one by one...

There is a reason why the `setPrimaryHDU()` is protected, because you don't want to accidentally use it for a HDU that should never be primary in the first place. 

As I said maybe I don't fully understand what you are trying to do. But, hopefully there is a better way to do it than exposing a protected method that could compromise the integrity of the files written...

**Comment by keastrid** [comment]
Maybe my understanding of how `Fits` write works isn't the best - does the `Fits` write not need to have all the HDUs in place (and therefore in memory) before writing? It doesn't look like `Fits#write` supports incremental writes as it dumps all HDUs it contains each time.

The issue with adding all HDUs to the `Fits` is memory concerns as the image(s) can get quite large.

**Comment by attipaci** [comment]
Yes, I think the prudent approach would be to add the first HDU to a `Fits`, and then write it out to a `FitsOutputStream` (which you can wrap around any output stream, such as a `FileOutputStream`). After that you can add additional HDUs using the `BasicHDU.write(ArrayDataOutput)` to the same stream. Something like:

```java
   File outFile;        // the file to which you want to write...
   
   ...  
  
   // Create the stream to which to write the HDUs as they come
   FitsOutputStream out = new FitsOutputStream(new FileOutputStream(outFile));

   //  Say your first HDU is an image, which you populate with data and header cards...
   ImageHDU primary;
 
   ...

   // When the first HDU is ready, you add it to a Fits and write it out.
   Fits fits = new Fits();
   fits.addHDU(primaryHDU);
   fits.write(out);          // Writes the first image as your primary HDU.

   ...

   // Then as you have additional HDUs, such as 'anotherHDU', you can append it to
   // the same FITS file (stream) as:
   anotherHDU.write(out);

   ...
 
   // When you are all done you can close
   out.close(); 
```

Does it make sense?

**Comment by keastrid** [comment]
Yes, that is nice! Also helps with the incremental writing of gzipped files I was struggling with, however the header corrections don't seem to ever be run. Attached is a diff of two fits files, `a` made with this method, and `b` made with all HDUs going through `fits.addHDU`.

[dump.txt](https://github.com/nom-tam-fits/nom-tam-fits/files/8308711/dump.txt)

**Comment by attipaci** [comment]
OK, I see your point. Let's think how we would want to do this if we started from scratch. What would an ideal interface look like for an incremental write case? My personal bias for interfaces is (a) keep them simple and intuitive, and (b) minimize the chance of misuse. In particular, the best would be an interface that just works without the chance of misuse that would result in corrupted FITS (e.g. ones in which some internal HDUs are marked as primary, or not being marked as XTENSION as above...)

If we find a satisfying answer to the above, we can see if we can modify the current framework to get there (or close to it). And if there is no better solution, we can just expose the relevant hidden methods as you suggested in the first place.

How does that sound to you as a plan for proceeding?

**Comment by attipaci** [comment]
One possibility is to add a `position()` method to the `ArrayDataOutput` interface that keeps that of where we are in the stream. Then `Header.write(ArrayDataOutput)` could add the relevant keywords for primary (if position = 0) or an extension (if position != 0). What do you think?

**Comment by keastrid** [comment]
Yes, that sounds good. Since its called when going through `BasicHDU.write` that should keep track of the position nicely.

**Comment by attipaci** [comment]
I've finally got around to make the relevant code changes, slated for 1.17.0 around June 15 (if all goes well). 

In the end I added a new interface, `FitsOutput` which wraps `ArrayDataOutput` and has a method to check if we are at the start of the output. Then, I changed `FitsOutputStream` and `FitsFile` to implement that interface instead of `ArrayDataOutput`, and I updated `BasicHDU.write()` to check if the write is at the start of the stream and call `setPrimaryHDU()` accordingly, as appropriate.

I think the changes do not alter the prior API in any way, extending it only. In any case because it does represent an API change, I think the correct thing to do is to bump the minor version number. But that's just book-keeping really. It should be the next release anyway.

(It would have been even better to add a dummy primary HDU up front if the first HDU cannot be made primary -- such as a binary table -- but unfortunately that breaks too many test cases, and perhaps some non-standard usage scenarios. So I let that part go.)

After the changes, incremental HDU writing should be super simple:

```java
   File outFile;        // the file to which you want to write...
   ...  
  
   // Create the stream to which to write the HDUs as they come
   FitsOutputStream out = new FitsOutputStream(new FileOutputStream(outFile));
   ...

   // you can append 'hdu' object to the FITS file (stream) as:
   hdu.write(out);
   ...

   // The first HDU will be set primary (if possible), and following HDUs will be extensions. 
   ...
 
   // When you are all done you can close
   out.close(); 
```
