### ISSUE TITLE
Fits::write() saves only HDUs loaded in memory

### ISSUE THREAD

**Issue by Pharisaeus** [nom-tam-fits/nom-tam-fits#371]
Calling `Fits::write()` will save to new file only HDUs which were loaded into memory instead of all HDUs of the input file. Not sure if this is a bug or a design choice, but the documentation is not clear, only stating that it "writes contents". As a result invoking:

```java
        try (var fits = new Fits("input.fits")) {
            fits.write("output.fits");
        }
```
Will create an empty output file, instead of, what someone might expect, a copy of the input file. The reason is:

```java
    private void write(ArrayDataOutput out) throws FitsException {
        for (BasicHDU<?> basicHDU : hduList) {
            basicHDU.write(out);
        }
    }
```
This iterates over `hduList` which only contains HDUs already loaded into memory.

**Comment by attipaci** [comment]
I'll think about that one. But, my first thought on this is that it's by design. `new Fits()` always creates an empty container. You either have to add HDUs to it or read them from an input to pupulate. Or you can mix and match...

I.e. the creation of the container and its contents are separate steps. And because this was always so since the beginning of time with nom-.tam-fits, changing it may break how it is used in existing applications. But, of course the documentation can be made clearer...

So, your first exasmple will be corrected as:

```java
    try (var fits = new Fits("input.fits")) {
        fits.read();
        fits.write("output.fits");
    }
```

**Comment by attipaci** [comment]
I don't disagree with your argument. There is a lot to this venerable library that does not follow the "principle of least astonishment". However, we need to be extremely wary of modifying existing behavior, no matter how "astonishing" it may be, because users have come to rely on it as it is.

I tend to agree that a lot of the design of nom-tam-fits is based on poor choices. But once the choices were made, we have to stick with them, s far as possible.

However, for similar reasons as this, I have started work on a new Java FITS library, that is independent on nom-tam-fits, and is meant to overcome of whole bunch of such design pitfalls. I plan to share the new project soon (in the next few months), and allow devs like you to chime in on finalizing the design before officiating a 1.0 release (maybe by the end of the year)...
