### ISSUE TITLE
HIERARCH + LongsStrings issue

### ISSUE THREAD

**Issue by nasamaher** [nom-tam-fits/nom-tam-fits#44]
Hi,

The following code will fail to write the value correctly and will throw an exception when trying to read the header.  It DOES work if the value in the addValue() call is a bit shorter or a bit longer.

I think the Header writing code does not realize it needs a "& .. CONTINUE" in this situation because it is doing something like assuming the Key is only 8 characters.

Steve

```java

        FitsFactory.setUseHierarch(true);
        FitsFactory.setLongStringsEnabled(true);

        Fits f = new Fits();
        BasicHDU primaryHdu = FitsFactory.hduFactory(new float[0]);

        primaryHdu.getHeader().addValue("HIERARCH.TEST.THIS.LONG.HEADER",
                "aaaaaaaabbbbbbbbbcccccccccccdddddddddddeeeeeeeeeee", "");

        f.addHDU(primaryHdu);
        String filename = "img.fits";
        BufferedFile bf = new BufferedFile(filename, "rw");
        f.write(bf);
        bf.close();
        
        /*
         * This will fail ...
         */
        Header headerRewriter = new Fits(filename).getHDU(0).getHeader();
```

**Comment by ritchieGitHub** [comment]
great test case! thanks, will be included this weekend.

**Comment by ritchieGitHub** [comment]
fixed

**Comment by nasamaher** [comment]
This worked.

Funny, though, to also test lower-case keywords with HIERARCH I change to 

```java
        primaryHdu.getHeader().addValue("HIERARCH.test.this.long.header",
                "aaaaaaaabbbbbbbbbcccccccccccdddddddddddeeeeeeeeeee", "");
```

and this failed.  NOTE, I will probably be switching to ALL CAPS anyways for keywords so this is not a problem for me.

Thanks!!

**Comment by ritchieGitHub** [comment]
I didn't allow lowercase letters yet , for that I want to wait for @TomMcGlynn  opinion.

**Comment by TomMcGlynn** [comment]
The original definition of the HIERARCH keywords explicitly required that they use the same character set as regular keywords.  That's why the library doesn't allow lower case letters.  CFITSIO is much more forgiving. I don't know what other libraries do.

It seems to me that there are three positions to take:

  1. Forbid them entirely, throw an error when they are read and don't allow users to write them.
  2. Allow them on input but either forbid or strongly discourage them on output (e.g., one could
    translate the inputs to upper case when writing new hierarch keywords.
  3. Do the same as FITSIO and allow any printable characters.  Note however that this would be a potential breaking change when applied to "." characters which are now handled as separators.  Allowing lowercase letters wouldn't pose any issue.

If there are extant readers which choke on mixed case, then probably 3 is a bad idea.  We don't want to encourage files that will break elsewhere.  However 2 is probably fine regardless.  There may not be very many libraries that handle HIERARCH and if everyone else is already using 3 then going there -- at least to the extent of supporting mixed case -- is fine.

Without more information my suggestion would be to support reading mixed case (maybe it does already), but convert to upper case when writing new records possibly with a flag to allow this behavior to be overriden.

There is a move to allow mixed case more generally in FITS keywords so this is likely going to be acceptable at some point.

**Comment by ritchieGitHub** [comment]
@TomMcGlynn  same option here, I will implement that for 1.13.1
