### ISSUE TITLE
Header inheritance for derivative HDUs

### ISSUE THREAD

**Issue by robyww** [nom-tam-fits/nom-tam-fits#487]
Since you deprecated the `ImageHDU` constructor. I don't see a way to do the following:

```java
ImageHDU newHDU = new ImageHDU(header,imageData);
```

We use this for task like cropping. When we want all the headers to be the same as the original image HDU except for the data `NAXIS` headers. This also involves using the deprecated `header.setNaxis()` functions.

The `fits.makeHDU()` does not accept the same parameters and seem awkward for this task. Am I missing something?

_More_ - another use case is that 
- we take an existing HDU
- modify the image data
- want to create another HDU with the same headers but with the modified image data

**Comment by attipaci** [comment]
Hi @robyww,

The reason it is deprecated is because it can easily be misused, e.g. passing it a header and a data that are not mutually consistent. Also, it would allow you to set the same header for two completely different images, resulting in total chaos if both try to modify it. The library should never allow assigning the same header to two different HDUs. It's a really bad programming pattern...

I do however see the need to support your use case better, and perhaps we have to come up with a better way of doing that. My initial intuition, is that you'd first create a new `ImageHDU` with the cropped data, which will thus have the correct BITPIX and dimensions, and an otherwise empty header, and then copy over all 'other' (optional) header entries, e.g. via a new methods such as `Header.inherit(Header)`, which will migrate everything from the argument that is not already present.

You could already do this manually (it's not much more work):

```java
   ImageHDU origHDU = ...
   ImageHDU croppedHDU = (ImageHDU) FitsFactory.makeHDU(croppedData);

   Header origHeader = origHDU.getHeader();
   Header croppedHeader = croppedHDU.getHeader();
   HeaderCard c = null;

   // Migrate all header cards not already defined for the cropped header
   while ((c = origHeader.nextCard()) != null) {
       if (!croppedHeader.containsKey(c.getKey()) {
           croppedHeader.addLine(c);
       }
   }
```

Sure it's a tad bit more verbose than the old way of constructing a new `ImageData` with the wrong header, and then fixing it up, but this way you cannot leave the HDU with divergent header and data that could screw things up royally.

Also, I should note that the deprecated methods are still supported. They are marked as deprecated because in some future release (not before 2.0) they will be removed. However you should still be able to compile your old way with deprecations enabled.

I hope that helps. Let me know if you have issues with either of the ways I described.

**Comment by attipaci** [comment]
@robyww, If you don't mind, I'll move this issue to Discussions, as it does not really require a change in the library per se, it more of a question how to use it (either with the deprecated methods, or using a different approach). I'll wait for a few days for you to chime in, in case you feel there is actually something that must be 'fixed' in the library itself to make it work for your use case...

**Comment by robyww** [comment]
_sorry it took so long to respond, I got a little overloaded last week..._

This is a common use case for us to modify data and make a new FITS. I understand the issues you are concerned about. And yes, we always make clone of the header. I do think having a header clone function would be a nice feature.

However, it would be nice to have a one-to-one safe drop in replacement for `new ImageHDU(header,imageData)`. We have been using nom-tam-fits in [Firefly](https://github.com/Caltech-IPAC/firefly) for years (before github!) and we have this sort of code in several places.

However about something like this:
```java
ImageHDU newHDU = (ImageHDU)Fits.makeHDU(imageData, templateHeader); 
```
The above would make a copy of the header, add or replace important keys (NAXIS stuff, ect). Then create the correct image HDU.

**Comment by attipaci** [comment]
Hi @robyww,

What you suggest is not all that different from what I suggested (and implemented in PR #489), which is:

```java
  ImageHDU newHDU = (ImageHDU) Fits.makeHDU(imageData);
  newHDU.getHeader().inherit(templateHeader);
```

I'm not a big fan of the adding a new `Fits.makeHDU()` method, which basically just combines the above two lines, because it just adds yet another corner-case method that is nevertheless confusing to use (Does it use the header, or does it make a copy? does it modify the supplied header? What if I modify the header after passing it to that method?). It's another can of worms. If you really want a 1-line version as you suggested, you can write your own implementation, and put it anywhere, e.g. within the FireFly library, e.g. into a `FireflyFitsHelper` class:

```java
 public static ImageHDU getImageCopy(ImageData imageData, Header origHeader) {
    ImageHDU newHDU = (ImageHDU) Fits.makeHDU(imageData);
    newHDU.getHeader().inherit(templateHeader);
    return newHDU;
 }
```

Or, if you want it to be compatible with older nom.tam.fits, copy the longer code from the first example further above into your helper method body. Then, you can call this as:

```java
   ImageHDU newHDU = FireflyFitsHelper.getImageCopy(imageData, templateHeader);
```

pretty much what you suggested, without having to put this inside nom.tam.fits...

Would that work for you?

cheers,

-- Attila.

**Comment by robyww** [comment]
Some comments.

 - Of course, we can make our own routine, sounds like we will have to.
 - I personally have always been surprised the headers are not copied for a new HDU anyway. Maybe that is just the fortran roots that influence the nom-tam-fits library.
 - In general when you deprecate a function in an API you don't want to make it harder on the developer to do it the new way. 
 - If I was reading it in the documentation I think I would I find `newHDU.getHeader().inherit(templateHeader)` kind of confusing. You usually inherit at creation time not as a second step. Maybe if it was (`newHDU.getHeader().insetStuffThatDoesNonConfict(templateHeader)`)
 

Those are my thoughts, we will work with whatever you release, but we will be slower to adopt it if is requires more work.

**Comment by attipaci** [comment]
> * Of course, we can make our own routine, sounds like we will have to.

Great! Go for it.

> * I personally have always been surprised the headers are not copied for a new HDU anyway. Maybe that is just the fortran roots that influence the nom-tam-fits library.

I'm not sure I agree.  99% of people who deal with FITS want to just read data in, or else want to write their own data out. Your use case of makig a new FITS out of an existing FITS, and recycling some parts of the original are a pretty special use case. Others might do similar things, but the particular use case will determine what pars exactly will be recycled, and what is kept. I don't think there is a universal approach that fits all here. (It might fit you, but someone else might need it to work a little different).

> * In general when you deprecate a function in an API you don't want to make it harder on the developer to do it the new way.

Nobody is forced to find a new way. Just enable deprecations in your compiler options, and you are good to fly until 2.0. But, when 2.0 does come, then you'll have to find a new way. Until then, you are good to go with your old code. (I'm using the deprecated methods just fine in older code I wrote for nom.tam.fits 1.12)..

> * If I was reading it in the documentation I think I would I find `newHDU.getHeader().inherit(templateHeader)` kind of confusing. You usually inherit at creation time not as a second step. Maybe if it was (`newHDU.getHeader().insetStuffThatDoesNonConfict(templateHeader)`)

OK, we can all it something else. It's a draft for now. Would you prefer `merge()` instead of `inherit()`? I'm agnotic.

> Those are my thoughts, we will work with whatever you release, but we will be slower to adopt it if is requires more work.

Please just enable deprecations in your compilation. Is that so complicated? I have no intention of making any developer's life difficult. On the contrary. I think nom.tam.fits was awfully tricky to use, and the deprecations are there to try people avoid commong pitfalls. But you are still welcome to step into every one of them if so you wish. They are all present and still supported.
