### ISSUE TITLE
Header api

### ISSUE THREAD

**Issue by ritchieGitHub** [nom-tam-fits/nom-tam-fits#5]
We could vasly reduce the api methods by using the builder pattern for header values. her some examples of what i mean:

    c.add(CTYPE1.key(), new HeaderCard(CTYPE1.key(), "GLON-CAR", "Galactic Longitude"));

would become:

    c.addKeyed(CTYPE1.value("GLON-CAR").comment("Galactic Longitude")));

and:

    hdr.addValue(INSTRUME, "My very big telescope");

would become:

    hdr.addValue(INSTRUME.value("My very big telescope"));

because the typing of the values is then in the "header value" object the api reduces to one instead of one for every type.

**Comment by ritchieGitHub** [comment]
ready for review

**Comment by TomMcGlynn** [comment]
This seems like a perfectly reasonable addition given the new enumerated header values, but I don't see how it's going to really reduce the complexity of the interface since users will need to to be able to use the existing API to write header values that are not included in the enumeration.

Are you also planning 'generic' enumerations so in addition to CTYPE we also have
GENERIC_FLOAT which is placeholder for some use specifiable keyword?  Since enums
are each singletons, that probably can't really work.   We don't want to require the user
to extend the enums for all keywords they might be defining.  

Or am I misunderstanding this entirely...  Still need to look at your actual code here.

**Comment by ritchieGitHub** [comment]
Code to include own enums is simple or even simpler just use a static as in the unit tests. But it would make the best programming solution for the user to define a enum (references are easy to find even if referenced from a jar (strings and statics won't work in jar's). For user enums definition I propse the service loader pattern, that's easy to use and easy to define)

**Comment by TomMcGlynn** [comment]
I'm completely confused as to what this means so I can't comment on it rationally.  Can you give examples of what you mean here.

**Comment by ritchieGitHub** [comment]
new api posponed
