### ISSUE TITLE
How to find out if specific header card is long string

### ISSUE THREAD

**Issue by supermartzin** [nom-tam-fits/nom-tam-fits#52]
Hi!

I wonder if there is some simple way how to find out if some existing `HeaderCard` contains longstring value (card that spreads along several lines) besides checking the length of value.

Another question: If there is a longstring card in **header** and I don't use longstring support (`FitsFactory.setLongStringsEnabled(false)`) those card will be loaded into object correctly or I have to explicitly set the flag?

Thanks for answer in advance.

**Comment by ritchieGitHub** [comment]
if the LONGSTRN keyword is specified before the longstring itself  the longstring support will turn on automatically. if not the longstring will not be read correctly.

This will probably change in one of the next versions because longstings are entering the base standard, there support will not be an option any more.

**Comment by supermartzin** [comment]
I'm sorry but what do you mean by:
> if the LONGSTRN keyword is specified before the longstring itself

There is some special keyword for longstrings?

Anyway I solved it by turning the longstring support on by default so I don't need to check if card has longstring value.

Thanks!

**Comment by ritchieGitHub** [comment]
yes, this keyword specifies that the fits file can contain longstrings. default on is the best way!
