### ISSUE TITLE
Classpath in manifest

### ISSUE THREAD

**Issue by bogdanni** [nom-tam-fits/nom-tam-fits#590]
For some reason the jar package (1.19.1) picks up the following classpath packages in the manifest:

```
Class-Path: commons-compress-1.26.1.jar commons-codec-1.16.1.jar commons-io-2.15.1.jar commons-lang3-3.14.0.jar spotbugs-annotations-4.8.3.jar jsr305-3.0.2.jar jakarta.annotation-api-2.1.1.jar
```

Out of those, only commons-compress seems to be a true dependency.

**Comment by attipaci** [comment]
I wonder if one of the maven-dependencies is messing it up. It looks like it mixes up build / test dependencies with runtime deps. I'll see what if anything I can do to remedy it...

**Comment by attipaci** [comment]
@bogdanni, 

I think, I've found something. It turns out that the nom-tam-fits jar was has a `Main` class (under `nom.tam.fits.utilities`, which was added into the manifest. If I remove adding the `Main` class to the the manifest, then the resulting `MANIFEST.MF` is clean with no dependencies (note, that even `common-compress` is an optional dependency, not a required one as per the POM)... 

That `Main` class is really dumb too. I really don't understand why it was added (and when). 

I am inclined to remove it entirely from the library, as I don't think it has a place there. Let me know if you object that idea...

**Comment by bogdanni** [comment]
Weird stuff, no idea what is going on, I guess removing this should not hamper the use of the library...

**Comment by attipaci** [comment]
You can check out PR #591 if interested to see what the JAR looks like without those classes that defined a `main()` method (and only that).

**Comment by bogdanni** [comment]
Looks good to me, no more classpath in the manifest.
