### ISSUE TITLE
IFitsHeader errors? Should MaxImDLExt.BAYERPAT and MaxImDLExt.PIERSIDE both be String type instead of real?

### ISSUE THREAD

**Issue by attipaci** [nom-tam-fits/nom-tam-fits#656]
### Discussed in https://github.com/nom-tam-fits/nom-tam-fits/discussions/655

<div type='discussions-op-text'>

<sup>Originally posted by **johnmurphyastro** August 13, 2024</sup>
Hi, thanks for this superb library, and all the work that has gone into it.
A possible minor correction:
Should the IFitsHeader values for
**MaxImDLExt.BAYERPAT**
**MaxImDLExt.PIERSIDE**
be VALUE.STRING instead of VALUE.REAL ?

Also, does a predefined entry for **ROWORDER** exist? I have created my own, but it would be great if this was included.
Regards, John Murphy</div>

**Comment by johnmurphyastro** [comment]
At the moment, all entries in MaxImDLExt are set to VALUE.REAL, which seems unlikely.

**I suggest the following MaxImDLExt corrections:**

// BAYERPAT examples: "RGGB", "GRBG", "GBRG", "BGGR", "RGBG", "GRGB", "GBGR", or "BGRG"
BAYERPAT(VALUE.STRING, "Image Bayer color pattern"),

// MaxIm DL Version 6.05 sets this to a blank string in my images. I've not seen it used else where.
FLIPSTAT(VALUE.ANY, "status of pier flip"),

MaxIm DL Version 6.05 sets this to an integer value
FOCUSPOS(VALUE.INTEGER, "Focuser position in steps"),

// I've never seen this used, but VALUE.REAL seams unlikely.
INPUTFMT(VALUE.ANY, "format of file"),

// MaxIm DL Version 6.07 sets this to "EAST" or "WEST" in my images.
// Other software sets it to "East" or "West"
PIERSIDE(VALUE.STRING, "Side-of-pier status"),

// MaxIm DL Version 6.07 sets this to "Raw" in my images
READOUTM(VALUE.STRING, "Readout Mode for the camera"),

**The following would be great additions (frequently used with amateur cameras):**

ANGLE(VALUE.REAL, "Image angle"),

// "2017-01-03T02:41:24" or "2024-02-24T22:23:33.054"
DATE_LOC("DATE-LOC", VALUE.STRING, "Time of observation (local)"),

// Always true or false
FLIPPED(VALUE.LOGICAL, "Is image flipped"),

FOCRATIO(VALUE.REAL, "Focal ratio"),

// Very common since CMOS cameras became popular
OFFSET(VALUE.INTEGER, "Camera offset setting"),

// "TOP-DOWN" or "BOTTOM-UP"
ROWORDER(VALUE.STRING, "FITS image orientation"),

// Synonyms of other entries, but frequently used
CCDXBIN(VALUE.INTEGER, "Binning factor in width"),
CCDYBIN(VALUE.INTEGER, "Binning factor in height"),
FOCPOS(VALUE.INTEGER, "Focuser position in steps"),
FOCTEMP(VALUE.REAL, "Focuser temperature readout")

CLOUDCVR(VALUE.REAL, "[percent] Cloud cover"),
HUMIDITY(VALUE.REAL, "[percent] relative humidity"),
DEWPOINT(VALUE.REAL, "[degC] Dew point"),
AMBTEMP(VALUE.REAL, "[degC] Ambient air temperature"),
WINDSPD(VALUE.REAL, "[kph] Wind speed"),
WINDDIR(VALUE.REAL, "[deg] Wind direction: 0=N, 180=S, 90=E, 270=W"),
PRESSURE(VALUE.REAL, "[hPa] Air pressure")

Regards, John Murphy

**Comment by attipaci** [comment]
Thanks @johnmurphyastro,

I've started with cleaning up the mess for the various extensions. See PR #657. I will incorporate the proposed changes above next (later today). Thanks for the good work on collecting them!

**Comment by attipaci** [comment]
As for the suggested additions: if these are not part of the MaxIm DL standard, then I suggest we put these into a new enum, such as `CommonExt` or `CamerasExt` (whichever you prefer)...

**Comment by johnmurphyastro** [comment]
I think CommonExt would be a great name for the new enum.
I have attached the FITS headers from 5 different camera programs, and I will go through these today so we can include all the common FITS extensions.
Thanks, John Murphy 

[FITS Header formats.zip](https://github.com/user-attachments/files/16612091/FITS.Header.formats.zip)
