### ISSUE TITLE
TableData Columns are returned as String[][]

### ISSUE THREAD

**Issue by JonCook** [nom-tam-fits/nom-tam-fits#79]
Hi,

Getting into the dark corners of our system (it has around 2.5million lines of code, roughly the same size as Linux) I have uncovered a fits file which is used for calibration purposes or alike.

It seems now with the latest version/snapshot some columns are returned as String[][] and in older versions certainly 1.06 this was not the case the column was returned as a String[] containing the data. Our code doesn't know how to handle String[][] so we can't read this FITS anymore. Maybe I could add some handling but I would like to understand a bit why this has changed.

I made a little test client and will make a PR containing the fits for testing/debugging.
```java
public static void main(String[] args) throws FitsException, IOException {
        try (Fits fits = new Fits("map_one_source_a_level_1_cal.fits")) {
            BasicHDU<?> hdu = fits.getHDU(1);
            nom.tam.fits.TableData data = (nom.tam.fits.TableData ) hdu.getData();

            Object[] columns = new Object[data.getNCols()];
            for (int i = 0; i < columns.length; i++) {
                Object column = data.getColumn(i);
                if (column instanceof String[][]) {
                    System.out.println("Column number " + i + " with ugly type: " + column + " is a String[][]");
                }
                //System.out.println("Column number " + i + " with ugly type: " + column);
                columns[i] = column;
            }
        }
    }
```
The output:
```
Column number 12 with ugly type: [[Ljava.lang.String;@1e6d1014 is a String[][]
Column number 13 with ugly type: [[Ljava.lang.String;@76707e36 is a String[][]
Column number 14 with ugly type: [[Ljava.lang.String;@614ddd49 is a String[][]
Column number 15 with ugly type: [[Ljava.lang.String;@1f554b06 is a String[][]
Column number 16 with ugly type: [[Ljava.lang.String;@694e1548 is a String[][]
Column number 17 with ugly type: [[Ljava.lang.String;@1c3a4799 is a String[][]
Column number 18 with ugly type: [[Ljava.lang.String;@131276c2 is a String[][]
```
This is what is now returned by getColumn for this String[][] - column 12
```
[[Channel_No.	Sim	JPL/RAL, 1	NaN	R1, 2	61	D16, 3	141	T1, 4	30	B16, 5	45	C15, 6	14	A15, 7	60	D15, 8	29	B15, 9	44	C14, 10	59	D14, 11	13	A14, 12	12	A13, 13	28	B14, 14	43	C13, 15	27	B13, 16	58	D13, 17	11	A12, 18	42	C12, 19	57	D12, 20	26	B12, 21	72	E11, 22	10	A11, 23	41	C11, 24	25	B11, 25	62	E1, 26	77	F1, 27	142	T2, 28	108	H1, 29	93	G1, 30	124	J1, 31	109	H2, 32	78	F2, 33	125	J2, 34	94	G2, 35	110	H3, 36	126	J3, 37	63	E2, 38	79	F3, 39	95	G3, 40	111	H4, 41	127	J4, 42	64	E3, 43	80	F4, 44	96	G4, 45	112	H5, 46	65	E4, 47	128	J5, 48	81	F5, 49	51	D6, 50	20	B6, 51	35	C5, 52	4	A5, 53	66	E5, 54	19	B5, 55	50	D5, 56	34	C4, 57	3	A4, 58	49	D4, 59	18	B4, 60	33	C3, 61	17	B3, 62	2	A3, 63	1	A2, 64	48	D3, 65	32	C2, 66	16	B2, 67	47	D2, 68	0	A1, 69	31	C1, 70	15	B1, 71	139	DP1, 72	46	D1, 73	88	F12, 74	134	J11, 75	73	E12, 76	119	H12, 77	104	G12, 78	89	F13, 79	74	E13, 80	135	J12, 81	120	H13, 82	105	G13, 83	90	F14, 84	75	E14, 85	136	J13, 86	121	H14, 87	106	G14, 88	137	J14, 89	91	F15, 90	122	H15, 91	138	J15, 92	107	G15, 93	123	H16, 94	140	DP2, 95	92	F16, 96	76	E15, 97	56	D11, 98	9	A10, 99	71	E10, 100	40	C10, 101	24	B10, 102	55	D10, 103	8	A9, 104	70	E9, 105	39	C9, 106	23	B9, 107	54	D9, 108	7	A8, 109	38	C8, 110	69	E8, 111	53	D8, 112	22	B8, 113	37	C7, 114	68	E7, 115	6	A7, 116	52	D7, 117	21	B7, 118	36	C6, 119	67	E6, 120	5	A6, 121	97	G5, 122	113	H6, 123	129	J6, 124	82	F6, 125	98	G6, 126	114	H7, 127	83	F7, 128	130	J7, 129	99	G7, 130	115	H8, 131	84	F8, 132	100	G8, 133	131	J8, 134	85	F9, 135	116	H9, 136	101	G9, 137	132	J9, 138	86	F10, 139	117	H10, 140	102	G10, 141	87	F11, 142	133	J10, 143	118	H11, 144	103	G11]]
```
Before it was identical but remove the start and end [] e.g)
```
[Channel_No.	Sim	JPL/RAL, 1	NaN	R1, 2	61	D16, 3	141	T1, 4	30	B16, 5	45	C15, 6	14	A15, 7	60	D15, 8	29	B15, 9	44	C14, 10	59	D14, 11	13	A14, 12	12	A13, 13	28	B14, 14	43	C13, 15	27	B13, 16	58	D13, 17	11	A12, 18	42	C12, 19	57	D12, 20	26	B12, 21	72	E11, 22	10	A11, 23	41	C11, 24	25	B11, 25	62	E1, 26	77	F1, 27	142	T2, 28	108	H1, 29	93	G1, 30	124	J1, 31	109	H2, 32	78	F2, 33	125	J2, 34	94	G2, 35	110	H3, 36	126	J3, 37	63	E2, 38	79	F3, 39	95	G3, 40	111	H4, 41	127	J4, 42	64	E3, 43	80	F4, 44	96	G4, 45	112	H5, 46	65	E4, 47	128	J5, 48	81	F5, 49	51	D6, 50	20	B6, 51	35	C5, 52	4	A5, 53	66	E5, 54	19	B5, 55	50	D5, 56	34	C4, 57	3	A4, 58	49	D4, 59	18	B4, 60	33	C3, 61	17	B3, 62	2	A3, 63	1	A2, 64	48	D3, 65	32	C2, 66	16	B2, 67	47	D2, 68	0	A1, 69	31	C1, 70	15	B1, 71	139	DP1, 72	46	D1, 73	88	F12, 74	134	J11, 75	73	E12, 76	119	H12, 77	104	G12, 78	89	F13, 79	74	E13, 80	135	J12, 81	120	H13, 82	105	G13, 83	90	F14, 84	75	E14, 85	136	J13, 86	121	H14, 87	106	G14, 88	137	J14, 89	91	F15, 90	122	H15, 91	138	J15, 92	107	G15, 93	123	H16, 94	140	DP2, 95	92	F16, 96	76	E15, 97	56	D11, 98	9	A10, 99	71	E10, 100	40	C10, 101	24	B10, 102	55	D10, 103	8	A9, 104	70	E9, 105	39	C9, 106	23	B9, 107	54	D9, 108	7	A8, 109	38	C8, 110	69	E8, 111	53	D8, 112	22	B8, 113	37	C7, 114	68	E7, 115	6	A7, 116	52	D7, 117	21	B7, 118	36	C6, 119	67	E6, 120	5	A6, 121	97	G5, 122	113	H6, 123	129	J6, 124	82	F6, 125	98	G6, 126	114	H7, 127	83	F7, 128	130	J7, 129	99	G7, 130	115	H8, 131	84	F8, 132	100	G8, 133	131	J8, 134	85	F9, 135	116	H9, 136	101	G9, 137	132	J9, 138	86	F10, 139	117	H10, 140	102	G10, 141	87	F11, 142	133	J10, 143	118	H11, 144	103	G11]
```

Thanks for any help
Jon

**Comment by JonCook** [comment]
PR pending - https://github.com/nom-tam-fits/blackbox-images/pulls

**Comment by ritchieGitHub** [comment]
@TomMcGlynn this is one for you! I am not yet in table internels.

**Comment by JonCook** [comment]
Maybe it is related to this change (clue in the title).
https://github.com/nom-tam-fits/nom-tam-fits/commit/dfe375f8b7d1ce56ebcef404bd8bd32cfdd33531
or previously
https://github.com/nom-tam-fits/nom-tam-fits/commit/46a5a20cca2e45df961f9b3e3d75d335997067b9

Do you think it is a regression? Thanks.

**Comment by TomMcGlynn** [comment]
I confirm that the behavior seems to have changed starting I believe in v1.13.0.  However as I read the FITS header it appears that both the new behavior is correct.  Below is an extract from the FITS header describing the columns in question:

TFORM13 = '3335A   '           /
TFORM14 = '2162A   '           /
TFORM15 = '1127A   '           /
TFORM16 = '92A     '           /
TFORM17 = '858A    '           /
TFORM18 = '552A    '           /
TFORM19 = '282A    '           /
TFORM20 = '7A      '           /
TFORM21 = '24A     '           /
COMMENT
COMMENT  *** Column dimensions (2 D or greater) ***
COMMENT
TDIM13  = '(23, 145)'          /
TDIM14  = '(23, 94)'           /                             
TDIM15  = '(23, 49)'           /
TDIM16  = '(23, 4) '           /
TDIM17  = '(6, 143)'           /
TDIM18  = '(6, 92) '           /
TDIM19  = '(6, 47) '           /

The TDIM entries are requesting that the columns be interpreted as 2-D arrays.  There was some work in release 1.13 dealing with building up tables that are defined row by row that may have fixed this apparent error. It looks like multidimensional strings were seriously broken in prior versions.   It looks like they could be built using explicit string arrays, but not read properly from existing files.

Two things muddied the waters here: we're dealing with strings, and the table has only a single row.  FITS has no native format for strings, it used character arrays.  The FITS library tries to understand where strings are being used and typically takes the last dimension of character arrays and transforms them into Strings.  E.g., for the thirteenth column, with FITS index 13 and Java index 12, 
we see TDIM is 23,145.  This means that each row of the column is an array of 145 strings each of which have a maximum length of 23 characters.  So if we ask what the object representing the column should be, it should have a first index which represent the row number, and a second index which indicates which of the 145 stings we want for the given row.  Hence the String[][] now returned.  However for this particular FITS file there is only a single row.  So it is actually convenient -- but wrong -- when the earlier versions of the library returned a String[145] array.

To see why that's wrong consider what would happen when there were two rows to the table?  In fact what happens then is that it returns a String[290] array which is clearly wrong since there is no way for the user to easily extract the column values for a given row.  The type of the column should not depend on the number of rows in the table.

If this correct but new behavior is problematic let me know and we can think about how you might proceed.

**Comment by TomMcGlynn** [comment]
It seems likely that one of those was the culprit, but as discussed 
elsewhere the current behavior seem to be correct (or at least correcter 
:) rather than the old version -- which is manifestly broken on multirow 
tables with multidimensional strings.   If you can update your code to 
use the proper behavior that might be the most robust solution,. However 
if that's unfeasible  we could jigger a little kludge in some private 
version that for single row tables suppresses the first index for 
multidimensional strings, but that doesn't seem optimal.

     Tom


Jonathan Cook wrote:

**Comment by JonCook** [comment]
Hi, thanks for investing. I've updated our code to handle this so no changes required I think on your side. Thanks again. Jon
