### ISSUE TITLE
Hierarch keywords convention

### ISSUE THREAD

**Issue by attipaci** [nom-tam-fits/nom-tam-fits#87]
Some (non-critical) issues with hierarch keywords (in 1.14.2):

-- The cfitsio specification (https://heasarc.gsfc.nasa.gov/docs/software/fitsio/c/f_user/node28.html) explicitly requires an empty space on both sides of the '=' character. It is consistent with the original ESO convention (http://fits.gsfc.nasa.gov/registry/hierarch/hierarch.pdf). Currently, '=' is immediately after the key. I.e.:

we have: `HIERARCH key= value`
we should have `HIERARCH key = value`

Note, a fix should still be able to parse keywords written earlier without the extra space.

-- The cfitsio specification  allows hierarch keywords to contain ASCII characters from 32 to 126 except '='. However, reading the header reports duplicate keys for the following two entries:

```
  HIERARCH key= ...
  HIERARCH [key]= ...
```

Yet, these are not duplicates but proper separate keywords 'key' and '[key]' in the given range of acceptable characters. (cfitsio convention)

**Comment by ritchieGitHub** [comment]
I think, when I understoud tom correctly that here the fits standard rules and only standard key charaters are allowed. More this weekend

**Comment by attipaci** [comment]
Hi Ritchie,


Don't worry now. There is no urgency...

Here is some more reference material -- the original ESO convention:

   http://fits.gsfc.nasa.gov/registry/hierarch/hierarch.pdf

According to this, the use of spaces instead of dots is in fact the 
recommended approach (so I will modify my comments accordingly).

It does not say anything about range of acceptable characters. However, 
the cfitsio documentation (the link on the issue report) might be a 
practical guide here, since cfitsio is the de facto standard tool for 
creating/editing FITS files...

They allow ASCII characters between 32 and 126 (except '=').

Let me know this weekend if I can help. (I'm not familiar with the 
internals of handling standard keywords vs hierarch keywords, so I don't 
want to botch it by making my own stupid edits...)

-- A.

**Comment by wcleveland** [comment]
HIERARCH is a COMMENT card which explains why bytes 9 and 10 should not contain "= " (decimal 61 followed by decimal 32). They accomplish this by requiring the keyword HIERARCH to always end with a SPACE making bytes 9 and 10 contain " =" (decimal 32 followed by decimal 61).

It's not really part of the FITS standard it's just an agreed convention taking advantage of how comment cards are defined.

Small correction to attipaci's comment:
You are allowed to have the '=' (decimal 61) anywhere within bytes 9 through 80, you just can't have bytes 9 and 10 contain '= ' (decimal 61 followed by decimal 32) unless the keyword is COMMENT, HISTORY, or bytes 1 through 8 contains decimal 32 (BLANK).

This is important since the HIERARCH keyword created during the ESO convention allows for:

HIERARCH ESO TEL FOCU SCALE = 1.489 / (deg/m) Focus length = 5.36"/mm

translates into: ESO.TEL.FOCU.SCALE = 1.489
with the comment: (deg/m) Focus length = 5.36"/mm

Maybe it would be better if HeaderCard handle these as comments and conventions (including this one) could be handled within a separate class using the raw card buffer. 

After a long drive, I saw this in my email and I can't explain why I answered it. 

From the version 3.0 of the FITS standard:

4.1.2.2. Value indicator (bytes 9 and 10)
If the two ASCII characters ‘=␣’ (decimal 61 followed by decimal 32) are present in bytes 9 and 10 of the keyword record this indicates that the keyword has a value field associated with it, unless it is one of the commentary keywords defined in Sect. 4.4.2 (i.e., a HISTORY, COMMENT, or completely blank keyword name) which by definition have no value.

4.4.2.4. Commentary keywords
These keywords provide commentary information about the contents or history of the FITS file and may occur any number of times in a header. These keywords shall have no associated value even if the value indicator characters ‘=␣’ appear in bytes 9 and 10 (hence it is recommended that these keywords not contain the value indicator). Bytes 9 through 80 may contain any of the restricted set of ASCII text characters, decimal 32 through 126 (hexadecimal 20 through 7E).

**Comment by wcleveland** [comment]
I want add that HIERARCH= 1.23 is still a valid key/value header card in the FITS standard and should probably still treated as one.

**Comment by ritchieGitHub** [comment]
I think the parsing must be done the same way as the formatting is done. With an external configurable parser. The task of the parser would be to get the key from the hierarch string, so I will update the regexp to allow the whole range of characters. And add a parse method to the IHierarchKeyFormatter interface.

**Comment by ritchieGitHub** [comment]
added a test case (still ignored) that I think must pass to stratify the specification. What do you two think?

**Comment by attipaci** [comment]
The relevant changes to processing `HIERARCH` have been merged, and ready to be released in 1.15.3. The changes satisfies the following requirements:

- All `HIERARCH` keywords that are written by this library can be parsed back without errors/warnings (previously that was not true, since the writing did not restrict the keys but the reading did!).
- There is no restriction on the characters that can be used in the keyword component after HIERARCH, other that they cannot use spaces (including tab, CR, LF), '.' or '='.
- The simple FITS card from the example of @wcleveland (`HIERARCH= 1.23`) is properly parsed too. (And I added a test case for that scenario also.)
 
I have also fixed and enabled the test case Ritchie created for this ealier.
