### ISSUE TITLE
concentrate double parsing / formatting

### ISSUE THREAD

**Issue by ritchieGitHub** [nom-tam-fits/nom-tam-fits#88]
For ASCII tables there are some extremely fast double/float print to/parse from string methods:

```
nom.tam.util.ByteParser.getDouble(int)
nom.tam.util.ByteFormatter.format(double, byte[], int, int)
nom.tam.util.ByteFormatter.format(float, byte[], int, int)
```

these should be harmonized with the header card double printing

**Comment by ritchieGitHub** [comment]
Attention, just discovered that the cast of a float to a double is a bad thing to do because it loses a lot of precision. 
(double)500.055f = 500.05499267578125d
Double.parseDouble(Float.toString(500.055f)) = 500.055d
so we must also check the code for these cases and replace them.

**Comment by ritchieGitHub** [comment]
just for the record the best sollution is:
```
new BigDecimal(floatValue, MathContext.DECIMAL32);
```
so to convert a float to an exact same double:
```
new BigDecimal(floatValue, MathContext.DECIMAL32).doubleValue();
```

**Comment by wcleveland** [comment]
Converting from a float to a double does not lose precision. The value stays exactly the same. 
0.055 can not be exactly represented in binary. 
The toString(float) function expects less precision than toString(double) and rounds the result at a lower precision than the double version.

I wouldn't make changes to the code. I'm still not convinced that floats or doubles should be converted to BigDecimals.

**Comment by ritchieGitHub** [comment]
The SO best answer describes it very good. Floats are not distinct vales. Due to that a float has far more virtual presision as it can really represent. When casting the float value directly to a double these virtual presision is transfered in the double as part of the real presion. In case of calculations this is OK most of the times because you more or less know that you are working with floats and doubles that have precision "problems". But when specifying values to the header and simular situations the virtual presion that becomes real presision changes the values in a unexpected way for the reader. An duplicating the code for every data type is not a road I want to enter 😄

**Comment by wcleveland** [comment]
I think we are getting caught in hypotheticals. There is nothing wrong with using doubles to hold values from either floats or doubles if it means it reduces redundant code. I don't see floats used in science much and if they are being used it is the caller that assumes the risk not the library.

My tests are simple. I use CFITSIO as the reference implementation. If nom-tam-fits produces the same values then it's a PASS if it doesn't it's a FAIL. The exception being that if nothing can be done to make it exact but it is close enough then it's a MAYBE :) (known issue not enough to stop release).

I don't see speed being an issue since I'm creating very large files and I am IO bound more than CPU bound. I'll be more than happy to test the additions and see if it actually results in faster writing. If it's faster and the resulting file matches the reference implementation then it's a win. ;)

**Comment by ritchieGitHub** [comment]
Yes! But very interesting stuff, it explain s a few bugs I had in the past. Don't think it will be faster, but it is less code and that means less chances for errors to peep in the edges... ;-)

If speed is an issue, 2.0 will be interesting for you, there we wan't to switch completely to memory mapped files.

**Comment by wcleveland** [comment]
Cool! Lack of time is what kept me from making a memory mapped version of a FITS library. Also I found that memory mapped IO help reading more than writing.

TZERO support is my next goal in my fork. Currently, my application has to handle the details and it would be nice if it was handled by the library.

**Comment by attipaci** [comment]
The existing code, even after the PRs, is still very quirky, and has some pretty ugly pitfalls, e.g. #169. A lot of it can be simplified, and the linked PR should address a fait bit of it...
